# Virtual Hosts
#
# <VirtualHost _default_:80>
#   ServerName localhost
#   ServerAlias localhost
#   DocumentRoot "${INSTALL_DIR}/www"
#   <Directory "${INSTALL_DIR}/www/">
#     Options +Indexes +Includes +FollowSymLinks +MultiViews
#     AllowOverride All
#     Require all granted
#   </Directory>
# </VirtualHost>
#



<VirtualHost *:80>
    ServerName devapp
    ServerAlias DESKTOP-9P0HD52
    DocumentRoot "c:/wamp64/www/devapp/public"
        Protocols h2c http/1.1
    <Directory "c:/wamp64/www/devapp/public/">
        Options +Indexes +Includes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/devapp-error.log"
    CustomLog "logs/devapp-access.log" combined
</VirtualHost>

<VirtualHost *:80>
    ServerName bommer.local
    ServerAlias www.bommer.local
    DocumentRoot "c:/wamp64/www/bommer"
    Protocols h2c http/1.1

    <Directory "c:/wamp64/www/bommer/">
        Options +Indexes +Includes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog "logs/bommer-error.log"
    CustomLog "logs/bommer-access.log" combined
</VirtualHost>
